// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElBacktop: typeof import("element-plus/es")["ElBacktop"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElLink: typeof import("element-plus/es")["ElLink"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    FloatingBtn: typeof import("./../components/FloatingBtn.vue")["default"];
    Imgs: typeof import("./../components/Imgs.vue")["default"];
    InfiniteScroll: typeof import("element-plus/es")["ElInfiniteScroll"];
    Loading: typeof import("element-plus/es")["ElLoadingDirective"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}

export {};
